### ISSUE TITLE
项目中提供的op_x64.dll似乎有bug

### ISSUE THREAD

**Issue by ZwkAlex** [flaot/OPTestTool#1]
在键盘为windows模式下，项目中的op_x64.dll（OPTestTool/Lib/op_x64.dll）keydown keyup keypress等操作无效，但是用原项目的op_x64.dll正常

**Comment by flaot** [comment]
群里发的不能保证是最新的  按照软件中页签“OPExport”上的教程进行编译并替换即可

**Comment by ZwkAlex** [comment]
为何我使用原项目的op_x64.dll 会报错 找不到名为“OP_CreateOP”的入口点
是不是我需要修改源码再编译

**Comment by flaot** [comment]
按照教程做
## 2.可以使用本测试工具目录下的op_xx.dll或者自己编译附带调用函数的DLL
### a.选择’使用外部OP工程‘ 
### b.选择语言'OP'->生成  
### c.编译op_xx.dll
```
b做的操作就是修改源码
```

**Comment by ZwkAlex** [comment]
明白了 感谢解惑
